
module.exports = {
	env: {
		NEXT_PUBLIC_HOST: process.env.NEXT_PUBLIC_HOST,
		NEXT_PUBLIC_VENDOR_ADDRESS: process.env.NEXT_PUBLIC_VENDOR_ADDRESS,
		NEXT_PUBLIC_RASPBERRY_PI_IP: process.env.NEXT_PUBLIC_RASPBERRY_PI_IP,
		NEXT_PUBLIC_NETWORK: process.env.NEXT_PUBLIC_NETWORK
	}
}